apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-chart.fullname" . }}
  labels:
    app: {{ include "django-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "django-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "django-chart.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_HOST
              value: {{ .Values.database.host | quote }}
            - name: DATABASE_PORT
              value: {{ .Values.database.port | quote }}
            - name: DATABASE_NAME
              value: {{ .Values.database.name | quote }}
            - name: DATABASE_USER
              value: {{ .Values.database.user | quote }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.database.password | quote }}
              # valueFrom:
              #   secretKeyRef:
              #     name: {{ include "django-chart.fullname" . }}-db-secret
              #     key: database-password
          ports:
            - containerPort: 8000
          resources:
{{- toYaml .Values.resources | nindent 12 }}
