apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-chart.fullname" . }}
  labels:
    app: {{ include "django-chart.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "django-chart.name" . }}
