version: '3.8'

services:
  vdt-api:
    build: .
    container_name: vdt-api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - DATABASE_NAME=vdt_db
      - DATABASE_USER=vinhbh
      - DATABASE_PASSWORD=123456789
      - DATABASE_HOST=192.168.144.143
      - DATABASE_PORT=31495
    ports:
      - 8000:8000
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
