# Generated by Django 5.0.6 on 2024-05-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='vdt_students',
        ),
    ]
