# Generated by Django 5.0.6 on 2024-05-20 17:04

from django.db import migrations

def insert_students(apps, schema_editor):
    Student = apps.get_model('base', 'Student')
    students = [
        {'full_name': 'Lê Minh Việt Anh',	'gender': 'Nam', 'school':	'Đại học Bách Khoa Hà Nội', 'email': 'anh.lmv.bkhn@gmail.com', 'phone':	'0394305264', 'country': 'Việt Nam'},
        {'full_name': 'Phạm Quang Bách',	'gender': 'Nam', 'school':	'VinUniversity', 'email': 'blu11235@gmail.com', 'phone':	'0866859929', 'country': 'Việt Nam'},
        {'full_name': 'Hoàng Bá Bảo',	'gender': 'Nam', 'school':	'Đại học Bách Khoa Hà Nội', 'email': 'bachdtm169@gmail.com', 'phone':	'0983155487', 'country': 'Việt Nam'},
        {'full_name': 'Phạm Minh Cường',	'gender': 'Nam', 'school':	'Đại học Công nghệ - Đại học Quốc gia Hà Nội', 'email': '20020098@vnu.edu.com', 'phone':	'0967809494', 'country': 'Việt Nam'},
        {'full_name': 'Trương Văn Độ',	'gender': 'Nam', 'school':	'Đại học Công nghệ - Đại học Quốc gia Hà Nội', 'email': 'truongvando1910@gmail.com', 'phone':	'0963047046', 'country': 'Việt Nam'},
        {'full_name': 'Hoàng Việt Dũng',	'gender': 'Nam', 'school':	'ITMO University', 'email': 'bungnud113@gmail.com', 'phone':	'0969698093', 'country': 'Nga'},
        {'full_name': 'Bùi Hoàng Dũng',	'gender': 'Nam', 'school':	'Đại học Bách Khoa Hà Nội', 'email': 'dung9d32k2@gmail.com', 'phone':	'0981268318', 'country': 'Việt Nam'},
        {'full_name': 'Bùi Trọng Dũng',	'gender': 'Nam', 'school':	'Đại học Bách Khoa Hà Nội', 'email': 'bui123456trongdung@gmail.com', 'phone':	'0931115699', 'country': 'Việt Nam'},
        {'full_name': 'Trần Thùy Dương',	'gender': 'Nữ',	'school': 'Đại học Công nghệ - Đại học Quốc gia Hà Nội', 'email': 'tranthuyduonghy2003@gmail.com', 'phone':	'0376065504', 'country': 'Việt Nam'},
        {'full_name': 'Quach Dang Giang',	'gender': 'Nam', 'school':	'Đại học Công nghệ Thông tin - Đại học Quốc gia TP.HCM', 'email': 'giang.dangquach@gmail.com', 'phone':	'0356886876', 'country': 'Việt Nam'},
        {'full_name': 'Nguyễn Thanh Hà',	'gender': 'Nam', 'school':	'Đại học Bách Khoa Hà Nội', 'email': 'captainnemot1k60@gmail.com', 'phone':	'0967571913', 'country': 'Việt Nam'},
        {'full_name': 'Nguyễn Thu Hà',	'gender': 'Nữ',	'school': 'Đại học Bách Khoa Hà Nội', 'email': 'nguyenthuhat1k60@gmail.com', 'phone':	'0858925333', 'country': 'Việt Nam'},
        {'full_name': 'Cù Xuân Hải',	'gender': 'Nam', 'school':	'ITMO University', 'email': 'xuanhai2708@gmail.com', 'phone':	'+79052735920', 'country': 'Nga'},
        {'full_name': 'Nguyễn Trung Hiếu',	'gender': 'Nam', 'school':	'Đại học Bách Khoa Hà Nội', 'email': 'hieu.nt230603@gmail.com', 'phone':	'0869347311', 'country': 'Việt Nam'},
        {'full_name': 'Đặng Việt Hoàng',	'gender': 'Nam', 'school':	'Đại học Bách Khoa Hà Nội', 'email': 'beetit338@gmail.com', 'phone':	'0866803327', 'country': 'Việt Nam'},
        {'full_name': 'Nguyễn Văn Hùng',	'gender': 'Nam', 'school':	'Đại học Bách Khoa Hà Nội', 'email': 'hungnv.itb@gmail.com', 'phone':	'0395334342', 'country': 'Việt Nam'},
        {'full_name': 'Nguyễn Quốc Hưng',	'gender': 'Nam', 'school':	'Đại học Bách Khoa Hà Nội', 'email': 'nothung209@gmail.com', 'phone':	'0982947213', 'country': 'Việt Nam'},
        {'full_name': 'Lê Minh Hương',	'gender': 'Nữ',	'school': 'Đại học Công nghệ - Đại học Quốc gia Hà Nội', 'email': 'lmhuong711@gmail.com', 'phone':	'0327182139', 'country': 'Việt Nam'},
        {'full_name': 'Ngo Dang Huy',	'gender': 'Nam', 'school':	'Đại học Công nghệ - Đại học Quốc gia Hà Nội', 'email': 'ngohuy658@gmail.com', 'phone':	'0343473387', 'country': 'Việt Nam'},
        {'full_name': 'Trần Quang Huy',	'gender': 'Nam', 'school':	'Học viện Công Nghệ Bưu Chính Viễn Thông', 'email': 'quanghuy1604nd@gmail.com', 'phone':	'0904845743', 'country': 'Việt Nam'},
        {'full_name': 'Trần Minh Huyền',	'gender': 'Nữ',	'school': 'Đại học Bách Khoa Hà Nội', 'email': 'huyen.cnh70@gmail.com', 'phone':	'0865776220', 'country': 'Việt Nam'},
        {'full_name': 'Nguyễn Đôn Thế Kiệt',	'gender': 'Nam', 'school':	'VinUniversity', 'email': 'viettel.strixthekiet@gmail.com', 'phone':	'0867288725', 'country': 'Việt Nam'},
        {'full_name': 'Lê Hoàng Trường',	'gender': 'Nam', 'school':	'ITMO University', 'email': 'natibatian@gmail.com', 'phone':	'09118984336', 'country': 'Nga'},
        {'full_name': 'Đào Quang Lợi',	'gender': 'Nam', 'school':	'Đại học Bách Khoa Hà Nội', 'email': 'loidao99@gmail.com', 'phone':	'0934829614', 'country': 'Việt Nam'},
        {'full_name': 'Nguyễn Tiến Long',	'gender': 'Nam', 'school':	'ITMO University', 'email': 'tienlong1106@gmail.com', 'phone':	'+79967695589', 'country': 'Nga'},
        {'full_name': 'Nguyen Quang Long',	'gender': 'Nam', 'school':	'Đại học Bách Khoa Hà Nội', 'email': 'long.nq.hust@gmail.com', 'phone':	'0869174722', 'country': 'Việt Nam'},
        {'full_name': 'Nguyễn Thị Ngọc Mai',	'gender': 'Nữ',	'school': 'Đại học Công nghệ - Đại học Quốc gia Hà Nội', 'email': 'maintn124@gmail.com', 'phone':	'0969918109', 'country': 'Việt Nam'},
        {'full_name': 'Đỗ Dương Mạnh',	'gender': 'Nam', 'school':	'ITMO University', 'email': 'domanhitmo@gmail.com', 'phone':	'0987779370', 'country': 'Nga'},
        {'full_name': 'Nguyễn Ngọc Minh',	'gender': 'Nam', 'school':	'Học viện Công Nghệ Bưu Chính Viễn Thông', 'email': 'minh.itptit@gmail.com', 'phone':	'0337191138', 'country': 'Việt Nam'},
        {'full_name': 'Vũ Thế Nam',	'gender': 'Nam', 'school':	'Đại học Công nghệ - Đại học Quốc gia Hà Nội', 'email': 'vuthenam.9.3.4@gmail.com', 'phone':	'09637070997', 'country': 'Việt Nam'},
        {'full_name': 'Ngô Công Bằng',	'gender': 'Nam', 'school':	'Học viện Công Nghệ Bưu Chính Viễn Thông', 'email': 'ngocongbang.ptit@gmail.com', 'phone':	'0963340608', 'country': 'Việt Nam'},
        {'full_name': 'Nguyễn Huy Thái',	'gender': 'Nam', 'school':	'Đại học Công nghệ - Đại học Quốc gia Hà Nội', 'email': 'nguyenhuythai15@gmail.com', 'phone':	'0946590882', 'country': 'Việt Nam'},
        {'full_name': 'Phan Khôi Nguyên',	'gender': 'Nam', 'school':	'Đại học Bách Khoa Hà Nội', 'email': 'khoinguyen6103@gmail.com', 'phone':	'0941777898', 'country': 'Việt Nam'},
        {'full_name': 'Đinh Việt Quang',	'gender': 'Nam', 'school':	'Đại học Bách Khoa Hà Nội', 'email': 'vietquang16012003@gmail.com', 'phone':	'0869963453', 'country': 'Việt Nam'},
        {'full_name': 'Nguyễn Chí Thành',	'gender': 'Nam', 'school':	'Đại học Bách Khoa Hà Nội', 'email': 'caitendenhonhat@gmail.com', 'phone':	'0833144638', 'country': 'Việt Nam'},
        {'full_name': 'Nguyễn Đình Tiến',	'gender': 'Nam', 'school':	'Đại học Bách Khoa Hà Nội', 'email': 'tiennguyen14122003@gmail.com', 'phone':	'0866920919', 'country': 'Việt Nam'},
        {'full_name': 'Đỗ Thu Trang',	'gender': 'Nữ',	'school': 'Đại học Công nghệ - Đại học Quốc gia Hà Nội', 'email': 'thutrang25062k4@gmail.com', 'phone':	'0328663946', 'country': 'Việt Nam'},
        {'full_name': 'Nguyễn Thị Mỹ Tú',	'gender': 'Nữ',	'school': 'ITMO University', 'email': 'jasmine150720@gmail.com', 'phone':	'+79219430456', 'country': 'Nga'},
        {'full_name': 'Nguyễn Quang Tuấn',	'gender': 'Nam', 'school':	'ITMO University', 'email': 'quangtuanitmo18@gmail.com', 'phone':	'+79533626795', 'country': 'Nga'},
        {'full_name': 'Hoàng Minh Tuấn',	'gender': 'Nam', 'school':	'Học viện Công Nghệ Bưu Chính Viễn Thông', 'email': 'tibanh03@gmail.com', 'phone':	'0328511409', 'country': 'Việt Nam'},
        {'full_name': 'Phạm Mạnh Tuấn',	'gender': 'Nam', 'school':	'ITMO University', 'email': '7upnamk@gmail.com', 'phone':	'09219430423', 'country': 'Nga'},
        {'full_name': 'Bùi Hoàng Vinh',	'gender': 'Nam', 'school':	'Học viện Công Nghệ Bưu Chính Viễn Thông', 'email': 'hoangvinh1577@gmail.com', 'phone':	'0946902235', 'country': 'Việt Nam'}
    ]
    for student_data in students:
        Student.objects.create(**student_data)

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_student_gender_alter_student_school'),
    ]

    operations = [
        migrations.RunPython(insert_students),
    ]
