# Generated by Django 5.0.6 on 2024-06-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_insert_student_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='VdtUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=15, null=True)),
                ('full_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'vdt_users',
            },
        ),
    ]
