replicaCount: 1

image:
  repository: vinhbh/vdt_api
  tag: "2.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000
  nodePort: 30002

database:
  host: postgres-chart
  port: 5432
  name: vdt_db
  user: vinhbh
  password: "123456789"

resources: {}
